name: Hello World workflow CICD

# Events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    workflow_dispatch:

#jobs
jobs:
  hello_runner_one_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World of CICD
        run: echo "Hello World"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: say goodbye
        run: echo "good bye"
        shell: bash

