name: Make API Request

on:
  push:
    branches:
      - develop

jobs:
  make-api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make API Request
        id: api-request
        uses: muhfaris/request-action@v0.1.2
        with:
          url: "https://reqres.in/api/users"
          headers: |
            {
              "accept": "application/json"
            }
          body: |
            {
              "name": "morpheus",
              "job": "leader"
            }
          method: POST

      - name: Show API Response Status
        run: |
          echo "Response Status: ${{ steps.api-request.outputs.response-status }}"

      - name: Show API Response Data
        run: |
          echo "Response Data: ${{ steps.api-request.outputs.response-data }}"