name: Create comment on new issues
on:
  issues:
    types: [ opened ]

jobs:
  comment-on-issues:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

  create-comment:
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: 1
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment][1]
          
          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'

  update-comment:
    - name: Update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: 557858210
        body: |
          **Edit:** Some additional info
        reactions: eyes

  add-reactions:
    - name: Add reactions
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: 557858210
        reactions: |
          heart
          hooray
          laugh